import { observer } from "mobx-react-lite";
import React from "react";
import { useStore } from "../../app/stores/store";
import SecondPlayerCell from "../cell/OpponentCell";

export default observer(function OpponentField(){
    const { cellStore } = useStore();
    
    return(
        <>
            <table style={{marginTop: '50px'}}>
                <thead>
                    <th></th>
                    <th>0</th>
                    <th>1</th>
                    <th>2</th>
                    <th>3</th>
                    <th>4</th>
                    <th>5</th>
                    <th>6</th>
                    <th>7</th>
                    <th>8</th>
                    <th>9</th>
                </thead>
                <tbody>
                    {cellStore.opponentCells != null ? 
                        (
                            <>
                                <tr>
                                    <th>0</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[0].id}
                                        x={cellStore.opponentCells[0].x}
                                        y={cellStore.opponentCells[0].y}
                                        status={cellStore.opponentCells[0].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[1].id}
                                        x={cellStore.opponentCells[1].x}
                                        y={cellStore.opponentCells[1].y}
                                        status={cellStore.opponentCells[1].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[2].id}
                                        x={cellStore.opponentCells[2].x}
                                        y={cellStore.opponentCells[2].y}
                                        status={cellStore.opponentCells[2].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[3].id}
                                        x={cellStore.opponentCells[3].x}
                                        y={cellStore.opponentCells[3].y}
                                        status={cellStore.opponentCells[3].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[4].id}
                                        x={cellStore.opponentCells[4].x}
                                        y={cellStore.opponentCells[4].y}
                                        status={cellStore.opponentCells[4].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[5].id}
                                        x={cellStore.opponentCells[5].x}
                                        y={cellStore.opponentCells[5].y}
                                        status={cellStore.opponentCells[5].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[6].id}
                                        x={cellStore.opponentCells[6].x}
                                        y={cellStore.opponentCells[6].y}
                                        status={cellStore.opponentCells[6].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[7].id}
                                        x={cellStore.opponentCells[7].x}
                                        y={cellStore.opponentCells[7].y}
                                        status={cellStore.opponentCells[7].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[8].id}
                                        x={cellStore.opponentCells[8].x}
                                        y={cellStore.opponentCells[8].y}
                                        status={cellStore.opponentCells[8].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[9].id}
                                        x={cellStore.opponentCells[9].x}
                                        y={cellStore.opponentCells[9].y}
                                        status={cellStore.opponentCells[9].status} 
                                    />
                                </tr>
                                <tr>
                                    <th>1</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[10].id}
                                        x={cellStore.opponentCells[10].x}
                                        y={cellStore.opponentCells[10].y}
                                        status={cellStore.opponentCells[10].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[11].id}
                                        x={cellStore.opponentCells[11].x}
                                        y={cellStore.opponentCells[11].y}
                                        status={cellStore.opponentCells[11].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[12].id}
                                        x={cellStore.opponentCells[12].x}
                                        y={cellStore.opponentCells[12].y}
                                        status={cellStore.opponentCells[12].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[13].id}
                                        x={cellStore.opponentCells[13].x}
                                        y={cellStore.opponentCells[13].y}
                                        status={cellStore.opponentCells[13].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[14].id}
                                        x={cellStore.opponentCells[14].x}
                                        y={cellStore.opponentCells[14].y}
                                        status={cellStore.opponentCells[14].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[15].id}
                                        x={cellStore.opponentCells[15].x}
                                        y={cellStore.opponentCells[15].y}
                                        status={cellStore.opponentCells[15].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[16].id}
                                        x={cellStore.opponentCells[16].x}
                                        y={cellStore.opponentCells[16].y}
                                        status={cellStore.opponentCells[16].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[17].id}
                                        x={cellStore.opponentCells[17].x}
                                        y={cellStore.opponentCells[17].y}
                                        status={cellStore.opponentCells[17].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[18].id}
                                        x={cellStore.opponentCells[18].x}
                                        y={cellStore.opponentCells[18].y}
                                        status={cellStore.opponentCells[18].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[19].id}
                                        x={cellStore.opponentCells[19].x}
                                        y={cellStore.opponentCells[19].y}
                                        status={cellStore.opponentCells[19].status} 
                                    />
                                </tr>
                                <tr>
                                    <th>2</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[20].id}
                                        x={cellStore.opponentCells[20].x}
                                        y={cellStore.opponentCells[20].y}
                                        status={cellStore.opponentCells[20].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[21].id}
                                        x={cellStore.opponentCells[21].x}
                                        y={cellStore.opponentCells[21].y}
                                        status={cellStore.opponentCells[21].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[22].id}
                                        x={cellStore.opponentCells[22].x}
                                        y={cellStore.opponentCells[22].y}
                                        status={cellStore.opponentCells[22].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[23].id}
                                        x={cellStore.opponentCells[23].x}
                                        y={cellStore.opponentCells[23].y}
                                        status={cellStore.opponentCells[23].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[24].id}
                                        x={cellStore.opponentCells[24].x}
                                        y={cellStore.opponentCells[24].y}
                                        status={cellStore.opponentCells[24].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[25].id}
                                        x={cellStore.opponentCells[25].x}
                                        y={cellStore.opponentCells[25].y}
                                        status={cellStore.opponentCells[25].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[26].id}
                                        x={cellStore.opponentCells[26].x}
                                        y={cellStore.opponentCells[26].y}
                                        status={cellStore.opponentCells[26].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[27].id}
                                        x={cellStore.opponentCells[27].x}
                                        y={cellStore.opponentCells[27].y}
                                        status={cellStore.opponentCells[27].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[28].id}
                                        x={cellStore.opponentCells[28].x}
                                        y={cellStore.opponentCells[28].y}
                                        status={cellStore.opponentCells[28].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[29].id}
                                        x={cellStore.opponentCells[29].x}
                                        y={cellStore.opponentCells[29].y}
                                        status={cellStore.opponentCells[29].status} 
                                    />
                                </tr>
                                <tr>
                                    <th>3</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[30].id}
                                        x={cellStore.opponentCells[30].x}
                                        y={cellStore.opponentCells[30].y}
                                        status={cellStore.opponentCells[30].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[31].id}
                                        x={cellStore.opponentCells[31].x}
                                        y={cellStore.opponentCells[31].y}
                                        status={cellStore.opponentCells[31].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[32].id}
                                        x={cellStore.opponentCells[32].x}
                                        y={cellStore.opponentCells[32].y}
                                        status={cellStore.opponentCells[32].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[33].id}
                                        x={cellStore.opponentCells[33].x}
                                        y={cellStore.opponentCells[33].y}
                                        status={cellStore.opponentCells[33].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[34].id}
                                        x={cellStore.opponentCells[34].x}
                                        y={cellStore.opponentCells[34].y}
                                        status={cellStore.opponentCells[34].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[35].id}
                                        x={cellStore.opponentCells[35].x}
                                        y={cellStore.opponentCells[35].y}
                                        status={cellStore.opponentCells[35].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[36].id}
                                        x={cellStore.opponentCells[36].x}
                                        y={cellStore.opponentCells[36].y}
                                        status={cellStore.opponentCells[36].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[37].id}
                                        x={cellStore.opponentCells[37].x}
                                        y={cellStore.opponentCells[37].y}
                                        status={cellStore.opponentCells[37].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[38].id}
                                        x={cellStore.opponentCells[38].x}
                                        y={cellStore.opponentCells[38].y}
                                        status={cellStore.opponentCells[38].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[39].id}
                                        x={cellStore.opponentCells[39].x}
                                        y={cellStore.opponentCells[39].y}
                                        status={cellStore.opponentCells[39].status} 
                                    />
                                </tr>
                                <tr>
                                    <th>4</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[40].id}
                                        x={cellStore.opponentCells[40].x}
                                        y={cellStore.opponentCells[40].y}
                                        status={cellStore.opponentCells[40].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[41].id}
                                        x={cellStore.opponentCells[41].x}
                                        y={cellStore.opponentCells[41].y}
                                        status={cellStore.opponentCells[41].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[42].id}
                                        x={cellStore.opponentCells[42].x}
                                        y={cellStore.opponentCells[42].y}
                                        status={cellStore.opponentCells[42].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[43].id}
                                        x={cellStore.opponentCells[43].x}
                                        y={cellStore.opponentCells[43].y}
                                        status={cellStore.opponentCells[43].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[44].id}
                                        x={cellStore.opponentCells[44].x}
                                        y={cellStore.opponentCells[44].y}
                                        status={cellStore.opponentCells[44].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[45].id}
                                        x={cellStore.opponentCells[45].x}
                                        y={cellStore.opponentCells[45].y}
                                        status={cellStore.opponentCells[45].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[46].id}
                                        x={cellStore.opponentCells[46].x}
                                        y={cellStore.opponentCells[46].y}
                                        status={cellStore.opponentCells[46].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[47].id}
                                        x={cellStore.opponentCells[47].x}
                                        y={cellStore.opponentCells[47].y}
                                        status={cellStore.opponentCells[47].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[48].id}
                                        x={cellStore.opponentCells[48].x}
                                        y={cellStore.opponentCells[48].y}
                                        status={cellStore.opponentCells[48].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[49].id}
                                        x={cellStore.opponentCells[49].x}
                                        y={cellStore.opponentCells[49].y}
                                        status={cellStore.opponentCells[49].status} 
                                    />
                                </tr>
                                <tr>
                                    <th>5</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[50].id}
                                        x={cellStore.opponentCells[50].x}
                                        y={cellStore.opponentCells[50].y}
                                        status={cellStore.opponentCells[50].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[51].id}
                                        x={cellStore.opponentCells[51].x}
                                        y={cellStore.opponentCells[51].y}
                                        status={cellStore.opponentCells[51].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[52].id}
                                        x={cellStore.opponentCells[52].x}
                                        y={cellStore.opponentCells[52].y}
                                        status={cellStore.opponentCells[52].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[53].id}
                                        x={cellStore.opponentCells[53].x}
                                        y={cellStore.opponentCells[53].y}
                                        status={cellStore.opponentCells[53].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[54].id}
                                        x={cellStore.opponentCells[54].x}
                                        y={cellStore.opponentCells[54].y}
                                        status={cellStore.opponentCells[54].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[55].id}
                                        x={cellStore.opponentCells[55].x}
                                        y={cellStore.opponentCells[55].y}
                                        status={cellStore.opponentCells[55].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[56].id}
                                        x={cellStore.opponentCells[56].x}
                                        y={cellStore.opponentCells[56].y}
                                        status={cellStore.opponentCells[56].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[57].id}
                                        x={cellStore.opponentCells[57].x}
                                        y={cellStore.opponentCells[57].y}
                                        status={cellStore.opponentCells[57].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[58].id}
                                        x={cellStore.opponentCells[58].x}
                                        y={cellStore.opponentCells[58].y}
                                        status={cellStore.opponentCells[58].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[59].id}
                                        x={cellStore.opponentCells[59].x}
                                        y={cellStore.opponentCells[59].y}
                                        status={cellStore.opponentCells[59].status} 
                                    />
                                </tr>
                                <tr>
                                    <th>6</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[60].id}
                                        x={cellStore.opponentCells[60].x}
                                        y={cellStore.opponentCells[60].y}
                                        status={cellStore.opponentCells[60].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[61].id}
                                        x={cellStore.opponentCells[61].x}
                                        y={cellStore.opponentCells[61].y}
                                        status={cellStore.opponentCells[61].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[62].id}
                                        x={cellStore.opponentCells[62].x}
                                        y={cellStore.opponentCells[62].y}
                                        status={cellStore.opponentCells[62].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[63].id}
                                        x={cellStore.opponentCells[63].x}
                                        y={cellStore.opponentCells[63].y}
                                        status={cellStore.opponentCells[63].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[64].id}
                                        x={cellStore.opponentCells[64].x}
                                        y={cellStore.opponentCells[64].y}
                                        status={cellStore.opponentCells[64].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[65].id}
                                        x={cellStore.opponentCells[65].x}
                                        y={cellStore.opponentCells[65].y}
                                        status={cellStore.opponentCells[65].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[66].id}
                                        x={cellStore.opponentCells[66].x}
                                        y={cellStore.opponentCells[66].y}
                                        status={cellStore.opponentCells[66].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[67].id}
                                        x={cellStore.opponentCells[67].x}
                                        y={cellStore.opponentCells[67].y}
                                        status={cellStore.opponentCells[67].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[68].id}
                                        x={cellStore.opponentCells[68].x}
                                        y={cellStore.opponentCells[68].y}
                                        status={cellStore.opponentCells[68].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[69].id}
                                        x={cellStore.opponentCells[69].x}
                                        y={cellStore.opponentCells[69].y}
                                        status={cellStore.opponentCells[69].status} 
                                    />
                                </tr>
                                <tr>
                                    <th>7</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[70].id}
                                        x={cellStore.opponentCells[70].x}
                                        y={cellStore.opponentCells[70].y}
                                        status={cellStore.opponentCells[70].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[71].id}
                                        x={cellStore.opponentCells[71].x}
                                        y={cellStore.opponentCells[71].y}
                                        status={cellStore.opponentCells[71].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[72].id}
                                        x={cellStore.opponentCells[72].x}
                                        y={cellStore.opponentCells[72].y}
                                        status={cellStore.opponentCells[72].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[73].id}
                                        x={cellStore.opponentCells[73].x}
                                        y={cellStore.opponentCells[73].y}
                                        status={cellStore.opponentCells[73].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[74].id}
                                        x={cellStore.opponentCells[74].x}
                                        y={cellStore.opponentCells[74].y}
                                        status={cellStore.opponentCells[74].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[75].id}
                                        x={cellStore.opponentCells[75].x}
                                        y={cellStore.opponentCells[75].y}
                                        status={cellStore.opponentCells[75].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[76].id}
                                        x={cellStore.opponentCells[76].x}
                                        y={cellStore.opponentCells[76].y}
                                        status={cellStore.opponentCells[76].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[77].id}
                                        x={cellStore.opponentCells[77].x}
                                        y={cellStore.opponentCells[77].y}
                                        status={cellStore.opponentCells[77].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[78].id}
                                        x={cellStore.opponentCells[78].x}
                                        y={cellStore.opponentCells[78].y}
                                        status={cellStore.opponentCells[78].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[79].id}
                                        x={cellStore.opponentCells[79].x}
                                        y={cellStore.opponentCells[79].y}
                                        status={cellStore.opponentCells[79].status} 
                                    />
                                </tr>
                                <tr>
                                    <th>8</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[80].id}
                                        x={cellStore.opponentCells[80].x}
                                        y={cellStore.opponentCells[80].y}
                                        status={cellStore.opponentCells[80].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[81].id}
                                        x={cellStore.opponentCells[81].x}
                                        y={cellStore.opponentCells[81].y}
                                        status={cellStore.opponentCells[81].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[82].id}
                                        x={cellStore.opponentCells[82].x}
                                        y={cellStore.opponentCells[82].y}
                                        status={cellStore.opponentCells[82].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[83].id}
                                        x={cellStore.opponentCells[83].x}
                                        y={cellStore.opponentCells[83].y}
                                        status={cellStore.opponentCells[83].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[84].id}
                                        x={cellStore.opponentCells[84].x}
                                        y={cellStore.opponentCells[84].y}
                                        status={cellStore.opponentCells[84].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[85].id}
                                        x={cellStore.opponentCells[85].x}
                                        y={cellStore.opponentCells[85].y}
                                        status={cellStore.opponentCells[85].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[86].id}
                                        x={cellStore.opponentCells[86].x}
                                        y={cellStore.opponentCells[86].y}
                                        status={cellStore.opponentCells[86].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[87].id}
                                        x={cellStore.opponentCells[87].x}
                                        y={cellStore.opponentCells[87].y}
                                        status={cellStore.opponentCells[87].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[88].id}
                                        x={cellStore.opponentCells[88].x}
                                        y={cellStore.opponentCells[88].y}
                                        status={cellStore.opponentCells[88].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[89].id}
                                        x={cellStore.opponentCells[89].x}
                                        y={cellStore.opponentCells[89].y}
                                        status={cellStore.opponentCells[89].status} 
                                    />
                                </tr>
                                <tr>
                                    <th>9</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[90].id}
                                        x={cellStore.opponentCells[90].x}
                                        y={cellStore.opponentCells[90].y}
                                        status={cellStore.opponentCells[90].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[91].id}
                                        x={cellStore.opponentCells[91].x}
                                        y={cellStore.opponentCells[91].y}
                                        status={cellStore.opponentCells[91].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[92].id}
                                        x={cellStore.opponentCells[92].x}
                                        y={cellStore.opponentCells[92].y}
                                        status={cellStore.opponentCells[92].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[93].id}
                                        x={cellStore.opponentCells[93].x}
                                        y={cellStore.opponentCells[93].y}
                                        status={cellStore.opponentCells[93].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[94].id}
                                        x={cellStore.opponentCells[94].x}
                                        y={cellStore.opponentCells[94].y}
                                        status={cellStore.opponentCells[94].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[95].id}
                                        x={cellStore.opponentCells[95].x}
                                        y={cellStore.opponentCells[95].y}
                                        status={cellStore.opponentCells[95].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[96].id}
                                        x={cellStore.opponentCells[96].x}
                                        y={cellStore.opponentCells[96].y}
                                        status={cellStore.opponentCells[96].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[97].id}
                                        x={cellStore.opponentCells[97].x}
                                        y={cellStore.opponentCells[97].y}
                                        status={cellStore.opponentCells[97].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[98].id}
                                        x={cellStore.opponentCells[98].x}
                                        y={cellStore.opponentCells[98].y}
                                        status={cellStore.opponentCells[98].status} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[99].id}
                                        x={cellStore.opponentCells[99].x}
                                        y={cellStore.opponentCells[99].y}
                                        status={cellStore.opponentCells[99].status} 
                                    />
                                </tr>
                            </>
                        )
                        :
                        (
                            null
                        )
                    }
                </tbody>
            </table>
        </>
    )
})