import { observer } from "mobx-react-lite";
import React, { useEffect } from "react";
import { useStore } from "../../app/stores/store";
import SecondPlayerCell from "../cell/OpponentCell";

export default observer(function OpponentField(){
    const { cellStore } = useStore();
    
    return(
        <>
            <table style={{marginTop: '50px'}}>
                <thead>
                    <th></th>
                    <th>0</th>
                    <th>1</th>
                    <th>2</th>
                    <th>3</th>
                    <th>4</th>
                    <th>5</th>
                    <th>6</th>
                    <th>7</th>
                    <th>8</th>
                    <th>9</th>
                </thead>
                <tbody>
                    {cellStore.opponentCells != null ? 
                        (
                            <>
                                <tr>
                                    <th>0</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[0].id}
                                        x={cellStore.opponentCells[0].x}
                                        y={cellStore.opponentCells[0].y}
                                        cellStatus={cellStore.opponentCells[0].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[1].id}
                                        x={cellStore.opponentCells[1].x}
                                        y={cellStore.opponentCells[1].y}
                                        cellStatus={cellStore.opponentCells[1].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[2].id}
                                        x={cellStore.opponentCells[2].x}
                                        y={cellStore.opponentCells[2].y}
                                        cellStatus={cellStore.opponentCells[2].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[3].id}
                                        x={cellStore.opponentCells[3].x}
                                        y={cellStore.opponentCells[3].y}
                                        cellStatus={cellStore.opponentCells[3].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[4].id}
                                        x={cellStore.opponentCells[4].x}
                                        y={cellStore.opponentCells[4].y}
                                        cellStatus={cellStore.opponentCells[4].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[5].id}
                                        x={cellStore.opponentCells[5].x}
                                        y={cellStore.opponentCells[5].y}
                                        cellStatus={cellStore.opponentCells[5].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[6].id}
                                        x={cellStore.opponentCells[6].x}
                                        y={cellStore.opponentCells[6].y}
                                        cellStatus={cellStore.opponentCells[6].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[7].id}
                                        x={cellStore.opponentCells[7].x}
                                        y={cellStore.opponentCells[7].y}
                                        cellStatus={cellStore.opponentCells[7].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[8].id}
                                        x={cellStore.opponentCells[8].x}
                                        y={cellStore.opponentCells[8].y}
                                        cellStatus={cellStore.opponentCells[8].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[9].id}
                                        x={cellStore.opponentCells[9].x}
                                        y={cellStore.opponentCells[9].y}
                                        cellStatus={cellStore.opponentCells[9].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>1</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[10].id}
                                        x={cellStore.opponentCells[10].x}
                                        y={cellStore.opponentCells[10].y}
                                        cellStatus={cellStore.opponentCells[10].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[11].id}
                                        x={cellStore.opponentCells[11].x}
                                        y={cellStore.opponentCells[11].y}
                                        cellStatus={cellStore.opponentCells[11].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[12].id}
                                        x={cellStore.opponentCells[12].x}
                                        y={cellStore.opponentCells[12].y}
                                        cellStatus={cellStore.opponentCells[12].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[13].id}
                                        x={cellStore.opponentCells[13].x}
                                        y={cellStore.opponentCells[13].y}
                                        cellStatus={cellStore.opponentCells[13].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[14].id}
                                        x={cellStore.opponentCells[14].x}
                                        y={cellStore.opponentCells[14].y}
                                        cellStatus={cellStore.opponentCells[14].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[15].id}
                                        x={cellStore.opponentCells[15].x}
                                        y={cellStore.opponentCells[15].y}
                                        cellStatus={cellStore.opponentCells[15].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[16].id}
                                        x={cellStore.opponentCells[16].x}
                                        y={cellStore.opponentCells[16].y}
                                        cellStatus={cellStore.opponentCells[16].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[17].id}
                                        x={cellStore.opponentCells[17].x}
                                        y={cellStore.opponentCells[17].y}
                                        cellStatus={cellStore.opponentCells[17].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[18].id}
                                        x={cellStore.opponentCells[18].x}
                                        y={cellStore.opponentCells[18].y}
                                        cellStatus={cellStore.opponentCells[18].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[19].id}
                                        x={cellStore.opponentCells[19].x}
                                        y={cellStore.opponentCells[19].y}
                                        cellStatus={cellStore.opponentCells[19].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>2</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[20].id}
                                        x={cellStore.opponentCells[20].x}
                                        y={cellStore.opponentCells[20].y}
                                        cellStatus={cellStore.opponentCells[20].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[21].id}
                                        x={cellStore.opponentCells[21].x}
                                        y={cellStore.opponentCells[21].y}
                                        cellStatus={cellStore.opponentCells[21].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[22].id}
                                        x={cellStore.opponentCells[22].x}
                                        y={cellStore.opponentCells[22].y}
                                        cellStatus={cellStore.opponentCells[22].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[23].id}
                                        x={cellStore.opponentCells[23].x}
                                        y={cellStore.opponentCells[23].y}
                                        cellStatus={cellStore.opponentCells[23].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[24].id}
                                        x={cellStore.opponentCells[24].x}
                                        y={cellStore.opponentCells[24].y}
                                        cellStatus={cellStore.opponentCells[24].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[25].id}
                                        x={cellStore.opponentCells[25].x}
                                        y={cellStore.opponentCells[25].y}
                                        cellStatus={cellStore.opponentCells[25].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[26].id}
                                        x={cellStore.opponentCells[26].x}
                                        y={cellStore.opponentCells[26].y}
                                        cellStatus={cellStore.opponentCells[26].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[27].id}
                                        x={cellStore.opponentCells[27].x}
                                        y={cellStore.opponentCells[27].y}
                                        cellStatus={cellStore.opponentCells[27].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[28].id}
                                        x={cellStore.opponentCells[28].x}
                                        y={cellStore.opponentCells[28].y}
                                        cellStatus={cellStore.opponentCells[28].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[29].id}
                                        x={cellStore.opponentCells[29].x}
                                        y={cellStore.opponentCells[29].y}
                                        cellStatus={cellStore.opponentCells[29].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>3</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[30].id}
                                        x={cellStore.opponentCells[30].x}
                                        y={cellStore.opponentCells[30].y}
                                        cellStatus={cellStore.opponentCells[30].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[31].id}
                                        x={cellStore.opponentCells[31].x}
                                        y={cellStore.opponentCells[31].y}
                                        cellStatus={cellStore.opponentCells[31].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[32].id}
                                        x={cellStore.opponentCells[32].x}
                                        y={cellStore.opponentCells[32].y}
                                        cellStatus={cellStore.opponentCells[32].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[33].id}
                                        x={cellStore.opponentCells[33].x}
                                        y={cellStore.opponentCells[33].y}
                                        cellStatus={cellStore.opponentCells[33].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[34].id}
                                        x={cellStore.opponentCells[34].x}
                                        y={cellStore.opponentCells[34].y}
                                        cellStatus={cellStore.opponentCells[34].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[35].id}
                                        x={cellStore.opponentCells[35].x}
                                        y={cellStore.opponentCells[35].y}
                                        cellStatus={cellStore.opponentCells[35].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[36].id}
                                        x={cellStore.opponentCells[36].x}
                                        y={cellStore.opponentCells[36].y}
                                        cellStatus={cellStore.opponentCells[36].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[37].id}
                                        x={cellStore.opponentCells[37].x}
                                        y={cellStore.opponentCells[37].y}
                                        cellStatus={cellStore.opponentCells[37].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[38].id}
                                        x={cellStore.opponentCells[38].x}
                                        y={cellStore.opponentCells[38].y}
                                        cellStatus={cellStore.opponentCells[38].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[39].id}
                                        x={cellStore.opponentCells[39].x}
                                        y={cellStore.opponentCells[39].y}
                                        cellStatus={cellStore.opponentCells[39].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>4</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[40].id}
                                        x={cellStore.opponentCells[40].x}
                                        y={cellStore.opponentCells[40].y}
                                        cellStatus={cellStore.opponentCells[40].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[41].id}
                                        x={cellStore.opponentCells[41].x}
                                        y={cellStore.opponentCells[41].y}
                                        cellStatus={cellStore.opponentCells[41].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[42].id}
                                        x={cellStore.opponentCells[42].x}
                                        y={cellStore.opponentCells[42].y}
                                        cellStatus={cellStore.opponentCells[42].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[43].id}
                                        x={cellStore.opponentCells[43].x}
                                        y={cellStore.opponentCells[43].y}
                                        cellStatus={cellStore.opponentCells[43].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[44].id}
                                        x={cellStore.opponentCells[44].x}
                                        y={cellStore.opponentCells[44].y}
                                        cellStatus={cellStore.opponentCells[44].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[45].id}
                                        x={cellStore.opponentCells[45].x}
                                        y={cellStore.opponentCells[45].y}
                                        cellStatus={cellStore.opponentCells[45].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[46].id}
                                        x={cellStore.opponentCells[46].x}
                                        y={cellStore.opponentCells[46].y}
                                        cellStatus={cellStore.opponentCells[46].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[47].id}
                                        x={cellStore.opponentCells[47].x}
                                        y={cellStore.opponentCells[47].y}
                                        cellStatus={cellStore.opponentCells[47].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[48].id}
                                        x={cellStore.opponentCells[48].x}
                                        y={cellStore.opponentCells[48].y}
                                        cellStatus={cellStore.opponentCells[48].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[49].id}
                                        x={cellStore.opponentCells[49].x}
                                        y={cellStore.opponentCells[49].y}
                                        cellStatus={cellStore.opponentCells[49].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>5</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[50].id}
                                        x={cellStore.opponentCells[50].x}
                                        y={cellStore.opponentCells[50].y}
                                        cellStatus={cellStore.opponentCells[50].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[51].id}
                                        x={cellStore.opponentCells[51].x}
                                        y={cellStore.opponentCells[51].y}
                                        cellStatus={cellStore.opponentCells[51].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[52].id}
                                        x={cellStore.opponentCells[52].x}
                                        y={cellStore.opponentCells[52].y}
                                        cellStatus={cellStore.opponentCells[52].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[53].id}
                                        x={cellStore.opponentCells[53].x}
                                        y={cellStore.opponentCells[53].y}
                                        cellStatus={cellStore.opponentCells[53].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[54].id}
                                        x={cellStore.opponentCells[54].x}
                                        y={cellStore.opponentCells[54].y}
                                        cellStatus={cellStore.opponentCells[54].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[55].id}
                                        x={cellStore.opponentCells[55].x}
                                        y={cellStore.opponentCells[55].y}
                                        cellStatus={cellStore.opponentCells[55].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[56].id}
                                        x={cellStore.opponentCells[56].x}
                                        y={cellStore.opponentCells[56].y}
                                        cellStatus={cellStore.opponentCells[56].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[57].id}
                                        x={cellStore.opponentCells[57].x}
                                        y={cellStore.opponentCells[57].y}
                                        cellStatus={cellStore.opponentCells[57].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[58].id}
                                        x={cellStore.opponentCells[58].x}
                                        y={cellStore.opponentCells[58].y}
                                        cellStatus={cellStore.opponentCells[58].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[59].id}
                                        x={cellStore.opponentCells[59].x}
                                        y={cellStore.opponentCells[59].y}
                                        cellStatus={cellStore.opponentCells[59].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>6</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[60].id}
                                        x={cellStore.opponentCells[60].x}
                                        y={cellStore.opponentCells[60].y}
                                        cellStatus={cellStore.opponentCells[60].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[61].id}
                                        x={cellStore.opponentCells[61].x}
                                        y={cellStore.opponentCells[61].y}
                                        cellStatus={cellStore.opponentCells[61].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[62].id}
                                        x={cellStore.opponentCells[62].x}
                                        y={cellStore.opponentCells[62].y}
                                        cellStatus={cellStore.opponentCells[62].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[63].id}
                                        x={cellStore.opponentCells[63].x}
                                        y={cellStore.opponentCells[63].y}
                                        cellStatus={cellStore.opponentCells[63].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[64].id}
                                        x={cellStore.opponentCells[64].x}
                                        y={cellStore.opponentCells[64].y}
                                        cellStatus={cellStore.opponentCells[64].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[65].id}
                                        x={cellStore.opponentCells[65].x}
                                        y={cellStore.opponentCells[65].y}
                                        cellStatus={cellStore.opponentCells[65].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[66].id}
                                        x={cellStore.opponentCells[66].x}
                                        y={cellStore.opponentCells[66].y}
                                        cellStatus={cellStore.opponentCells[66].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[67].id}
                                        x={cellStore.opponentCells[67].x}
                                        y={cellStore.opponentCells[67].y}
                                        cellStatus={cellStore.opponentCells[67].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[68].id}
                                        x={cellStore.opponentCells[68].x}
                                        y={cellStore.opponentCells[68].y}
                                        cellStatus={cellStore.opponentCells[68].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[69].id}
                                        x={cellStore.opponentCells[69].x}
                                        y={cellStore.opponentCells[69].y}
                                        cellStatus={cellStore.opponentCells[69].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>7</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[70].id}
                                        x={cellStore.opponentCells[70].x}
                                        y={cellStore.opponentCells[70].y}
                                        cellStatus={cellStore.opponentCells[70].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[71].id}
                                        x={cellStore.opponentCells[71].x}
                                        y={cellStore.opponentCells[71].y}
                                        cellStatus={cellStore.opponentCells[71].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[72].id}
                                        x={cellStore.opponentCells[72].x}
                                        y={cellStore.opponentCells[72].y}
                                        cellStatus={cellStore.opponentCells[72].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[73].id}
                                        x={cellStore.opponentCells[73].x}
                                        y={cellStore.opponentCells[73].y}
                                        cellStatus={cellStore.opponentCells[73].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[74].id}
                                        x={cellStore.opponentCells[74].x}
                                        y={cellStore.opponentCells[74].y}
                                        cellStatus={cellStore.opponentCells[74].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[75].id}
                                        x={cellStore.opponentCells[75].x}
                                        y={cellStore.opponentCells[75].y}
                                        cellStatus={cellStore.opponentCells[75].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[76].id}
                                        x={cellStore.opponentCells[76].x}
                                        y={cellStore.opponentCells[76].y}
                                        cellStatus={cellStore.opponentCells[76].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[77].id}
                                        x={cellStore.opponentCells[77].x}
                                        y={cellStore.opponentCells[77].y}
                                        cellStatus={cellStore.opponentCells[77].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[78].id}
                                        x={cellStore.opponentCells[78].x}
                                        y={cellStore.opponentCells[78].y}
                                        cellStatus={cellStore.opponentCells[78].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[79].id}
                                        x={cellStore.opponentCells[79].x}
                                        y={cellStore.opponentCells[79].y}
                                        cellStatus={cellStore.opponentCells[79].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>8</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[80].id}
                                        x={cellStore.opponentCells[80].x}
                                        y={cellStore.opponentCells[80].y}
                                        cellStatus={cellStore.opponentCells[80].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[81].id}
                                        x={cellStore.opponentCells[81].x}
                                        y={cellStore.opponentCells[81].y}
                                        cellStatus={cellStore.opponentCells[81].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[82].id}
                                        x={cellStore.opponentCells[82].x}
                                        y={cellStore.opponentCells[82].y}
                                        cellStatus={cellStore.opponentCells[82].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[83].id}
                                        x={cellStore.opponentCells[83].x}
                                        y={cellStore.opponentCells[83].y}
                                        cellStatus={cellStore.opponentCells[83].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[84].id}
                                        x={cellStore.opponentCells[84].x}
                                        y={cellStore.opponentCells[84].y}
                                        cellStatus={cellStore.opponentCells[84].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[85].id}
                                        x={cellStore.opponentCells[85].x}
                                        y={cellStore.opponentCells[85].y}
                                        cellStatus={cellStore.opponentCells[85].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[86].id}
                                        x={cellStore.opponentCells[86].x}
                                        y={cellStore.opponentCells[86].y}
                                        cellStatus={cellStore.opponentCells[86].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[87].id}
                                        x={cellStore.opponentCells[87].x}
                                        y={cellStore.opponentCells[87].y}
                                        cellStatus={cellStore.opponentCells[87].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[88].id}
                                        x={cellStore.opponentCells[88].x}
                                        y={cellStore.opponentCells[88].y}
                                        cellStatus={cellStore.opponentCells[88].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[89].id}
                                        x={cellStore.opponentCells[89].x}
                                        y={cellStore.opponentCells[89].y}
                                        cellStatus={cellStore.opponentCells[89].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>9</th>
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[90].id}
                                        x={cellStore.opponentCells[90].x}
                                        y={cellStore.opponentCells[90].y}
                                        cellStatus={cellStore.opponentCells[90].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[91].id}
                                        x={cellStore.opponentCells[91].x}
                                        y={cellStore.opponentCells[91].y}
                                        cellStatus={cellStore.opponentCells[91].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[92].id}
                                        x={cellStore.opponentCells[92].x}
                                        y={cellStore.opponentCells[92].y}
                                        cellStatus={cellStore.opponentCells[92].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[93].id}
                                        x={cellStore.opponentCells[93].x}
                                        y={cellStore.opponentCells[93].y}
                                        cellStatus={cellStore.opponentCells[93].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[94].id}
                                        x={cellStore.opponentCells[94].x}
                                        y={cellStore.opponentCells[94].y}
                                        cellStatus={cellStore.opponentCells[94].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[95].id}
                                        x={cellStore.opponentCells[95].x}
                                        y={cellStore.opponentCells[95].y}
                                        cellStatus={cellStore.opponentCells[95].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[96].id}
                                        x={cellStore.opponentCells[96].x}
                                        y={cellStore.opponentCells[96].y}
                                        cellStatus={cellStore.opponentCells[96].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[97].id}
                                        x={cellStore.opponentCells[97].x}
                                        y={cellStore.opponentCells[97].y}
                                        cellStatus={cellStore.opponentCells[97].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[98].id}
                                        x={cellStore.opponentCells[98].x}
                                        y={cellStore.opponentCells[98].y}
                                        cellStatus={cellStore.opponentCells[98].cellStatus} 
                                    />
                                    <SecondPlayerCell
                                        id={cellStore.opponentCells[99].id}
                                        x={cellStore.opponentCells[99].x}
                                        y={cellStore.opponentCells[99].y}
                                        cellStatus={cellStore.opponentCells[99].cellStatus} 
                                    />
                                </tr>
                            </>
                        )
                        :
                        (
                            null
                        )
                    }
                </tbody>
            </table>
        </>
    )
})