import { observer } from "mobx-react-lite";
import React, { useEffect } from "react";
import { useStore } from "../../app/stores/store";
import FirstPlayerCell from "../cell/PlayerCell";

export default observer(function PlayerField(){
    const { userStore, cellStore, gameStore } = useStore();

    useEffect(() => {
        if(userStore.user!.name == userStore.game!.firstPlayerName)
        {
            cellStore.loadPlayerCells(userStore.game!.firstPlayerFieldId!);
            userStore.loadGoingStatus();
            gameStore.loadCountOfShipsAlive();
        }
        else
        {
            cellStore.loadPlayerCells(userStore.game!.secondPlayerFieldId!);
            userStore.loadGoingStatus();
            gameStore.loadCountOfShipsAlive();
        }
    });
    
    return(
        <>
            <table style={{marginTop: '50px'}}>
                <thead>
                    <th></th>
                    <th>0</th>
                    <th>1</th>
                    <th>2</th>
                    <th>3</th>
                    <th>4</th>
                    <th>5</th>
                    <th>6</th>
                    <th>7</th>
                    <th>8</th>
                    <th>9</th>
                </thead>
                <tbody>
                    {cellStore.playerCells != null ? 
                        (
                            <>
                                <tr>
                                    <th>0</th>
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[0].id}
                                        x={cellStore.playerCells[0].x}
                                        y={cellStore.playerCells[0].y}
                                        cellStatus={cellStore.playerCells[0].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[1].id}
                                        x={cellStore.playerCells[1].x}
                                        y={cellStore.playerCells[1].y}
                                        cellStatus={cellStore.playerCells[1].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[2].id}
                                        x={cellStore.playerCells[2].x}
                                        y={cellStore.playerCells[2].y}
                                        cellStatus={cellStore.playerCells[2].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[3].id}
                                        x={cellStore.playerCells[3].x}
                                        y={cellStore.playerCells[3].y}
                                        cellStatus={cellStore.playerCells[3].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[4].id}
                                        x={cellStore.playerCells[4].x}
                                        y={cellStore.playerCells[4].y}
                                        cellStatus={cellStore.playerCells[4].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[5].id}
                                        x={cellStore.playerCells[5].x}
                                        y={cellStore.playerCells[5].y}
                                        cellStatus={cellStore.playerCells[5].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[6].id}
                                        x={cellStore.playerCells[6].x}
                                        y={cellStore.playerCells[6].y}
                                        cellStatus={cellStore.playerCells[6].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[7].id}
                                        x={cellStore.playerCells[7].x}
                                        y={cellStore.playerCells[7].y}
                                        cellStatus={cellStore.playerCells[7].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[8].id}
                                        x={cellStore.playerCells[8].x}
                                        y={cellStore.playerCells[8].y}
                                        cellStatus={cellStore.playerCells[8].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[9].id}
                                        x={cellStore.playerCells[9].x}
                                        y={cellStore.playerCells[9].y}
                                        cellStatus={cellStore.playerCells[9].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>1</th>
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[10].id}
                                        x={cellStore.playerCells[10].x}
                                        y={cellStore.playerCells[10].y}
                                        cellStatus={cellStore.playerCells[10].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[11].id}
                                        x={cellStore.playerCells[11].x}
                                        y={cellStore.playerCells[11].y}
                                        cellStatus={cellStore.playerCells[11].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[12].id}
                                        x={cellStore.playerCells[12].x}
                                        y={cellStore.playerCells[12].y}
                                        cellStatus={cellStore.playerCells[12].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[13].id}
                                        x={cellStore.playerCells[13].x}
                                        y={cellStore.playerCells[13].y}
                                        cellStatus={cellStore.playerCells[13].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[14].id}
                                        x={cellStore.playerCells[14].x}
                                        y={cellStore.playerCells[14].y}
                                        cellStatus={cellStore.playerCells[14].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[15].id}
                                        x={cellStore.playerCells[15].x}
                                        y={cellStore.playerCells[15].y}
                                        cellStatus={cellStore.playerCells[15].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[16].id}
                                        x={cellStore.playerCells[16].x}
                                        y={cellStore.playerCells[16].y}
                                        cellStatus={cellStore.playerCells[16].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[17].id}
                                        x={cellStore.playerCells[17].x}
                                        y={cellStore.playerCells[17].y}
                                        cellStatus={cellStore.playerCells[17].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[18].id}
                                        x={cellStore.playerCells[18].x}
                                        y={cellStore.playerCells[18].y}
                                        cellStatus={cellStore.playerCells[18].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[19].id}
                                        x={cellStore.playerCells[19].x}
                                        y={cellStore.playerCells[19].y}
                                        cellStatus={cellStore.playerCells[19].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>2</th>
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[20].id}
                                        x={cellStore.playerCells[20].x}
                                        y={cellStore.playerCells[20].y}
                                        cellStatus={cellStore.playerCells[20].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[21].id}
                                        x={cellStore.playerCells[21].x}
                                        y={cellStore.playerCells[21].y}
                                        cellStatus={cellStore.playerCells[21].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[22].id}
                                        x={cellStore.playerCells[22].x}
                                        y={cellStore.playerCells[22].y}
                                        cellStatus={cellStore.playerCells[22].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[23].id}
                                        x={cellStore.playerCells[23].x}
                                        y={cellStore.playerCells[23].y}
                                        cellStatus={cellStore.playerCells[23].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[24].id}
                                        x={cellStore.playerCells[24].x}
                                        y={cellStore.playerCells[24].y}
                                        cellStatus={cellStore.playerCells[24].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[25].id}
                                        x={cellStore.playerCells[25].x}
                                        y={cellStore.playerCells[25].y}
                                        cellStatus={cellStore.playerCells[25].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[26].id}
                                        x={cellStore.playerCells[26].x}
                                        y={cellStore.playerCells[26].y}
                                        cellStatus={cellStore.playerCells[26].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[27].id}
                                        x={cellStore.playerCells[27].x}
                                        y={cellStore.playerCells[27].y}
                                        cellStatus={cellStore.playerCells[27].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[28].id}
                                        x={cellStore.playerCells[28].x}
                                        y={cellStore.playerCells[28].y}
                                        cellStatus={cellStore.playerCells[28].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[29].id}
                                        x={cellStore.playerCells[29].x}
                                        y={cellStore.playerCells[29].y}
                                        cellStatus={cellStore.playerCells[29].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>3</th>
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[30].id}
                                        x={cellStore.playerCells[30].x}
                                        y={cellStore.playerCells[30].y}
                                        cellStatus={cellStore.playerCells[30].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[31].id}
                                        x={cellStore.playerCells[31].x}
                                        y={cellStore.playerCells[31].y}
                                        cellStatus={cellStore.playerCells[31].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[32].id}
                                        x={cellStore.playerCells[32].x}
                                        y={cellStore.playerCells[32].y}
                                        cellStatus={cellStore.playerCells[32].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[33].id}
                                        x={cellStore.playerCells[33].x}
                                        y={cellStore.playerCells[33].y}
                                        cellStatus={cellStore.playerCells[33].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[34].id}
                                        x={cellStore.playerCells[34].x}
                                        y={cellStore.playerCells[34].y}
                                        cellStatus={cellStore.playerCells[34].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[35].id}
                                        x={cellStore.playerCells[35].x}
                                        y={cellStore.playerCells[35].y}
                                        cellStatus={cellStore.playerCells[35].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[36].id}
                                        x={cellStore.playerCells[36].x}
                                        y={cellStore.playerCells[36].y}
                                        cellStatus={cellStore.playerCells[36].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[37].id}
                                        x={cellStore.playerCells[37].x}
                                        y={cellStore.playerCells[37].y}
                                        cellStatus={cellStore.playerCells[37].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[38].id}
                                        x={cellStore.playerCells[38].x}
                                        y={cellStore.playerCells[38].y}
                                        cellStatus={cellStore.playerCells[38].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[39].id}
                                        x={cellStore.playerCells[39].x}
                                        y={cellStore.playerCells[39].y}
                                        cellStatus={cellStore.playerCells[39].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>4</th>
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[40].id}
                                        x={cellStore.playerCells[40].x}
                                        y={cellStore.playerCells[40].y}
                                        cellStatus={cellStore.playerCells[40].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[41].id}
                                        x={cellStore.playerCells[41].x}
                                        y={cellStore.playerCells[41].y}
                                        cellStatus={cellStore.playerCells[41].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[42].id}
                                        x={cellStore.playerCells[42].x}
                                        y={cellStore.playerCells[42].y}
                                        cellStatus={cellStore.playerCells[42].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[43].id}
                                        x={cellStore.playerCells[43].x}
                                        y={cellStore.playerCells[43].y}
                                        cellStatus={cellStore.playerCells[43].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[44].id}
                                        x={cellStore.playerCells[44].x}
                                        y={cellStore.playerCells[44].y}
                                        cellStatus={cellStore.playerCells[44].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[45].id}
                                        x={cellStore.playerCells[45].x}
                                        y={cellStore.playerCells[45].y}
                                        cellStatus={cellStore.playerCells[45].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[46].id}
                                        x={cellStore.playerCells[46].x}
                                        y={cellStore.playerCells[46].y}
                                        cellStatus={cellStore.playerCells[46].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[47].id}
                                        x={cellStore.playerCells[47].x}
                                        y={cellStore.playerCells[47].y}
                                        cellStatus={cellStore.playerCells[47].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[48].id}
                                        x={cellStore.playerCells[48].x}
                                        y={cellStore.playerCells[48].y}
                                        cellStatus={cellStore.playerCells[48].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[49].id}
                                        x={cellStore.playerCells[49].x}
                                        y={cellStore.playerCells[49].y}
                                        cellStatus={cellStore.playerCells[49].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>5</th>
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[50].id}
                                        x={cellStore.playerCells[50].x}
                                        y={cellStore.playerCells[50].y}
                                        cellStatus={cellStore.playerCells[50].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[51].id}
                                        x={cellStore.playerCells[51].x}
                                        y={cellStore.playerCells[51].y}
                                        cellStatus={cellStore.playerCells[51].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[52].id}
                                        x={cellStore.playerCells[52].x}
                                        y={cellStore.playerCells[52].y}
                                        cellStatus={cellStore.playerCells[52].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[53].id}
                                        x={cellStore.playerCells[53].x}
                                        y={cellStore.playerCells[53].y}
                                        cellStatus={cellStore.playerCells[53].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[54].id}
                                        x={cellStore.playerCells[54].x}
                                        y={cellStore.playerCells[54].y}
                                        cellStatus={cellStore.playerCells[54].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[55].id}
                                        x={cellStore.playerCells[55].x}
                                        y={cellStore.playerCells[55].y}
                                        cellStatus={cellStore.playerCells[55].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[56].id}
                                        x={cellStore.playerCells[56].x}
                                        y={cellStore.playerCells[56].y}
                                        cellStatus={cellStore.playerCells[56].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[57].id}
                                        x={cellStore.playerCells[57].x}
                                        y={cellStore.playerCells[57].y}
                                        cellStatus={cellStore.playerCells[57].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[58].id}
                                        x={cellStore.playerCells[58].x}
                                        y={cellStore.playerCells[58].y}
                                        cellStatus={cellStore.playerCells[58].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[59].id}
                                        x={cellStore.playerCells[59].x}
                                        y={cellStore.playerCells[59].y}
                                        cellStatus={cellStore.playerCells[59].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>6</th>
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[60].id}
                                        x={cellStore.playerCells[60].x}
                                        y={cellStore.playerCells[60].y}
                                        cellStatus={cellStore.playerCells[60].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[61].id}
                                        x={cellStore.playerCells[61].x}
                                        y={cellStore.playerCells[61].y}
                                        cellStatus={cellStore.playerCells[61].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[62].id}
                                        x={cellStore.playerCells[62].x}
                                        y={cellStore.playerCells[62].y}
                                        cellStatus={cellStore.playerCells[62].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[63].id}
                                        x={cellStore.playerCells[63].x}
                                        y={cellStore.playerCells[63].y}
                                        cellStatus={cellStore.playerCells[63].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[64].id}
                                        x={cellStore.playerCells[64].x}
                                        y={cellStore.playerCells[64].y}
                                        cellStatus={cellStore.playerCells[64].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[65].id}
                                        x={cellStore.playerCells[65].x}
                                        y={cellStore.playerCells[65].y}
                                        cellStatus={cellStore.playerCells[65].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[66].id}
                                        x={cellStore.playerCells[66].x}
                                        y={cellStore.playerCells[66].y}
                                        cellStatus={cellStore.playerCells[66].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[67].id}
                                        x={cellStore.playerCells[67].x}
                                        y={cellStore.playerCells[67].y}
                                        cellStatus={cellStore.playerCells[67].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[68].id}
                                        x={cellStore.playerCells[68].x}
                                        y={cellStore.playerCells[68].y}
                                        cellStatus={cellStore.playerCells[68].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[69].id}
                                        x={cellStore.playerCells[69].x}
                                        y={cellStore.playerCells[69].y}
                                        cellStatus={cellStore.playerCells[69].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>7</th>
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[70].id}
                                        x={cellStore.playerCells[70].x}
                                        y={cellStore.playerCells[70].y}
                                        cellStatus={cellStore.playerCells[70].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[71].id}
                                        x={cellStore.playerCells[71].x}
                                        y={cellStore.playerCells[71].y}
                                        cellStatus={cellStore.playerCells[71].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[72].id}
                                        x={cellStore.playerCells[72].x}
                                        y={cellStore.playerCells[72].y}
                                        cellStatus={cellStore.playerCells[72].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[73].id}
                                        x={cellStore.playerCells[73].x}
                                        y={cellStore.playerCells[73].y}
                                        cellStatus={cellStore.playerCells[73].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[74].id}
                                        x={cellStore.playerCells[74].x}
                                        y={cellStore.playerCells[74].y}
                                        cellStatus={cellStore.playerCells[74].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[75].id}
                                        x={cellStore.playerCells[75].x}
                                        y={cellStore.playerCells[75].y}
                                        cellStatus={cellStore.playerCells[75].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[76].id}
                                        x={cellStore.playerCells[76].x}
                                        y={cellStore.playerCells[76].y}
                                        cellStatus={cellStore.playerCells[76].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[77].id}
                                        x={cellStore.playerCells[77].x}
                                        y={cellStore.playerCells[77].y}
                                        cellStatus={cellStore.playerCells[77].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[78].id}
                                        x={cellStore.playerCells[78].x}
                                        y={cellStore.playerCells[78].y}
                                        cellStatus={cellStore.playerCells[78].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[79].id}
                                        x={cellStore.playerCells[79].x}
                                        y={cellStore.playerCells[79].y}
                                        cellStatus={cellStore.playerCells[79].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>8</th>
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[80].id}
                                        x={cellStore.playerCells[80].x}
                                        y={cellStore.playerCells[80].y}
                                        cellStatus={cellStore.playerCells[80].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[81].id}
                                        x={cellStore.playerCells[81].x}
                                        y={cellStore.playerCells[81].y}
                                        cellStatus={cellStore.playerCells[81].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[82].id}
                                        x={cellStore.playerCells[82].x}
                                        y={cellStore.playerCells[82].y}
                                        cellStatus={cellStore.playerCells[82].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[83].id}
                                        x={cellStore.playerCells[83].x}
                                        y={cellStore.playerCells[83].y}
                                        cellStatus={cellStore.playerCells[83].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[84].id}
                                        x={cellStore.playerCells[84].x}
                                        y={cellStore.playerCells[84].y}
                                        cellStatus={cellStore.playerCells[84].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[85].id}
                                        x={cellStore.playerCells[85].x}
                                        y={cellStore.playerCells[85].y}
                                        cellStatus={cellStore.playerCells[85].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[86].id}
                                        x={cellStore.playerCells[86].x}
                                        y={cellStore.playerCells[86].y}
                                        cellStatus={cellStore.playerCells[86].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[87].id}
                                        x={cellStore.playerCells[87].x}
                                        y={cellStore.playerCells[87].y}
                                        cellStatus={cellStore.playerCells[87].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[88].id}
                                        x={cellStore.playerCells[88].x}
                                        y={cellStore.playerCells[88].y}
                                        cellStatus={cellStore.playerCells[88].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[89].id}
                                        x={cellStore.playerCells[89].x}
                                        y={cellStore.playerCells[89].y}
                                        cellStatus={cellStore.playerCells[89].cellStatus} 
                                    />
                                </tr>
                                <tr>
                                    <th>9</th>
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[90].id}
                                        x={cellStore.playerCells[90].x}
                                        y={cellStore.playerCells[90].y}
                                        cellStatus={cellStore.playerCells[90].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[91].id}
                                        x={cellStore.playerCells[91].x}
                                        y={cellStore.playerCells[91].y}
                                        cellStatus={cellStore.playerCells[91].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[92].id}
                                        x={cellStore.playerCells[92].x}
                                        y={cellStore.playerCells[92].y}
                                        cellStatus={cellStore.playerCells[92].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[93].id}
                                        x={cellStore.playerCells[93].x}
                                        y={cellStore.playerCells[93].y}
                                        cellStatus={cellStore.playerCells[93].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[94].id}
                                        x={cellStore.playerCells[94].x}
                                        y={cellStore.playerCells[94].y}
                                        cellStatus={cellStore.playerCells[94].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[95].id}
                                        x={cellStore.playerCells[95].x}
                                        y={cellStore.playerCells[95].y}
                                        cellStatus={cellStore.playerCells[95].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[96].id}
                                        x={cellStore.playerCells[96].x}
                                        y={cellStore.playerCells[96].y}
                                        cellStatus={cellStore.playerCells[96].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[97].id}
                                        x={cellStore.playerCells[97].x}
                                        y={cellStore.playerCells[97].y}
                                        cellStatus={cellStore.playerCells[97].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[98].id}
                                        x={cellStore.playerCells[98].x}
                                        y={cellStore.playerCells[98].y}
                                        cellStatus={cellStore.playerCells[98].cellStatus} 
                                    />
                                    <FirstPlayerCell
                                        id={cellStore.playerCells[99].id}
                                        x={cellStore.playerCells[99].x}
                                        y={cellStore.playerCells[99].y}
                                        cellStatus={cellStore.playerCells[99].cellStatus} 
                                    />
                                </tr>
                            </>
                        )
                        :
                        (
                            null
                        )
                    }
                </tbody>
            </table>
        </>
    )
})